kind: Deployment
apiVersion: apps/v1
metadata:
    name: stemfinity
spec:
    replicas: 2
    selector:
        matchLabels:
            app: stemfinity
    template:
        metadata:
            labels:
                app: stemfinity
        spec:
            containers:
              - name: stemfinity
                image: localhost:5000/stemfinity
                imagePullPolicy: Always
                ports:
                    - containerPort: 80
            restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
    name: stemfinity
spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        nodePort: 31000
    selector:
        app: stemfinity